name: "Coverage Prologue"
description: "Installs lcov and generates the baseline coverage"
inputs:
  build-output-dir:
    required: true
    description: 'Build output directory'
  compiler:
    required: true
    description: 'Compiler in use'

runs:
  using: "composite"
  steps:
    - name: "Install lcov"
      if: ${{ inputs.compiler == 'gcc' }}
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y lcov

    - name: "Initialize 0% coverage baseline"
      if: ${{ inputs.compiler == 'gcc' }}
      shell: bash
      run: |
        lcov --capture --initial \
             --base-directory "$GITHUB_WORKSPACE" \
             --directory "${{ inputs.build-output-dir }}" \
             --output-file coverage.baseline \
             --ignore-errors mismatch

    - name: "LLVM profile env var"
      if: ${{ inputs.compiler == 'clang' }}
      shell: bash
      run: echo "LLVM_PROFILE_FILE=coverage.profraw" >> $GITHUB_ENV