name: "Benchmark Epilogue"
description: "Processes coverage information with lcov and uploads it to coveralls/codecov"
inputs:
  build-output-dir:
    required: true
    description: 'Build output directory'
runs:
  using: "composite"
  steps:
    # Download previous benchmark result from cache (if exists)
    - name: Download previous benchmark data
      uses: actions/cache@v4
      with:
        path: ./cache
        key: ${{ runner.os }}-benchmark

    - name: Store benchmark result
      uses: benchmark-action/github-action-benchmark@v1
      with:
        tool: 'googlecpp'
        # Where the output from the benchmark tool is stored
        output-file-path: ${{ inputs.build-output-dir }}/benchmark_result.json
        # Where the previous data file is stored
        external-data-json-path: ./cache/benchmark_result.json
        # Workflow will fail when an alert happens
        fail-on-alert: true
