name: "Benchmark Epilogue"
description: "Processes coverage information with lcov and uploads it to coveralls/codecov"
inputs:
  workspace:
    required: True
    description: "Source code / workspace"
  compiler:
    required: True
    description: 'Compiler used to build benchmark'
  os:
    required: True
    description: 'OS used to build benchmark'
  stdlib:
    required: True
    description: 'C++ standard library used to build benchmark'
  build-output-dir:
    required: true
    description: 'Build output directory'
  base_ref:
    required: true
    description: 'Base ref for PR/comparison'
  cpp_compiler:
    required: true
    description: 'Cpp compiler to use'
  c_compiler:
    required: true
    description: 'C compiler to use'
  build_type:
    required: true
    description: 'Build type (release/debug)'

runs:
  using: "composite"
  steps:
    - name: Checkout target branch (BASE)
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.base_ref }}

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install benchmark compare.py requirements
      shell: bash
      run: |
        pip install --upgrade setuptools
        pip install -r ${{ inputs.build-output-dir}}/_deps/benchmark-src/tools/requirements.txt

    - name: Benchmark Workflow
      shell: bash
      run: |
        mv ${{ inputs.build-output-dir }}/benchmark/benchmark_result.json ${{ inputs.build-output-dir }}/benchmark/benchmark_result_new.json
        cmake -B ${{ inputs.build-output-dir}} -S ${{ inputs.workspace }} \
          --preset benchmark_${{ inputs.os }}_${{ inputs.compiler }}_${{ inputs.stdlib }} \
          -DCMAKE_CXX_COMPILER=${{ inputs.cpp_compiler }} \
          -DCMAKE_C_COMPILER=${{ inputs.c_compiler }} \
          -DCMAKE_BUILD_TYPE=${{ inputs.build_type }}
        cmake --build ${{ inputs.build-output-dir}} --target benchmark --config ${{ inputs.build_type }} --parallel
        ctest --test-dir ${{ inputs.build-output-dir}} --build-config ${{ inputs.build_type }} --output-on-failure --parallel
        mv ${{ inputs.build-output-dir }}/benchmark/benchmark_result.json ${{ inputs.build-output-dir }}/benchmark/benchmark_result_ref.json

    - name: Compare Benchmarks
      shell: bash
      run: |
        python3 ${{ inputs.build-output-dir}}/_deps/benchmark-src/tools/compare.py benchmarks \
          ${{ inputs.build-output-dir }}/benchmark/benchmark_result_ref.json \
          ${{ inputs.build-output-dir }}/benchmark/benchmark_result_new.json \
          | tee ${{ inputs.build-output-dir }}/benchmark/comparison.txt

    - name: Archive benchmark results
      uses: actions/upload-artifact@v4
      with:
        name: benchmark_${{ inputs.os }}_${{ inputs.compiler }}_${{ inputs.stdlib }}_json
        path: |
          ${{ inputs.build-output-dir }}/benchmark/benchmark_result_ref.json
          ${{ inputs.build-output-dir }}/benchmark/benchmark_result_new.json
          ${{ inputs.build-output-dir }}/benchmark/comparison.txt
