name: "Coverage GCC"
description: "Installs lcov, generates the baseline coverage, runs tests, processes coverage and uploads reports"
inputs:
  build-output-dir:
    required: true
    description: 'Build output directory'
  GITHUB_TOKEN:
    required: true

runs:
  using: "composite"
  steps:
    - name: "Install lcov"
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y lcov

    - name: "Initialize 0% coverage baseline"
      shell: bash
      run: |
        lcov --capture --initial \
             --base-directory "$GITHUB_WORKSPACE" \
             --directory "${{ inputs.build-output-dir }}" \
             --output-file coverage.baseline \
             --ignore-errors mismatch

    - name: Test
      shell: bash
      run: ${{ inputs.build-output-dir }}/test/bitlib-tests

    - name: Generate Coverage Report
      shell: bash
      run: |
        # Capture actual coverage data after tests
        lcov --capture \
             --directory "${{ inputs.build-output-dir }}" \
             --output-file coverage_gcc.info \
             --ignore-errors mismatch

        # Combine with baseline
        lcov --add-tracefile coverage.baseline \
             --add-tracefile coverage_gcc.info\
             --output-file coverage_gcc.info

        # Clean the coverage report from system and external deps
        lcov --remove coverage_gcc.info \
             '/usr/*' \
             '*/_deps/*' \
             '*/include/bitlib/bit-algorithms/libpopcnt.h' \
             '*/test/inc/*' \
             '*/test/src/*' \
             --output-file coverage_gcc.info

        # Show a summary in the logs
        lcov --list coverage_gcc.info

        # Generate an HTML report
        genhtml coverage_gcc.info --output-directory out/coverage_gcc

    - name: Upload coverage artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: |
          out/coverage_gcc
          coverage.baseline
          coverage_gcc.info

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ inputs.GITHUB_TOKEN }}
        path-to-lcov: coverage_gcc.info

    - name: Upload to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: coverage_gcc.info
        flags: unittests
        name: codecov-coverage-report
